
app.eureka-server: eureka-server

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5


---
spring.config.activate.on-profile: docker
app.eureka-server: eureka-server
spring.cloud.config.uri: http://config-server:8888
