spring.application.name: edge-server

server.port: 8081

server.ssl:
  key-store-type: PKCS12
  key-store: classpath:keystore/edge.p12
  key-store-password: password
  key-alias: localhost


spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:

        - id: ms-user
          uri: lb://ms-user
          predicates:
            - Path=/ms-user/**
          filters:
            - StripPrefix=1

        - id: ms-user-swagger-ui
          uri: lb://ms-user
          predicates:
            - Path=/swagger-user/swagger-ui/**
          filters:
            - StripPrefix=1

        - id: ms-user-swagger-config
          uri: lb://ms-user
          predicates:
            - Path=/v3/api-docs/swagger-config
          filters:
            - StripPrefix=0


        - id: ms-user-swagger-api-docs-fix
          uri: lb://ms-user
          predicates:
            - Path=/v3/api-docs
          filters:
            - SetPath=/v3/api-docs



        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/ms-auth/**
          filters:
            - StripPrefix=1



        - id: ms-anuncios
          uri: lb://ms-anuncios
          predicates:
            - Path=/ms-anuncios/**
          filters:
            - StripPrefix=1

        # Rutas para ms rating
        - id: ms-rating
          uri: lb://ms-rating
          predicates:
            - Path=/ms-rating/**
          filters:
            - StripPrefix=1


        - id: eureka-web-start
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/


        - id: eureka-web-other
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/**



# Configuraci贸n para exponer endpoints de administraci贸n
#management.endpoint.gateway.enabled: true
#management.endpoint.health.show-details: "ALWAYS"
#management.endpoints.web.exposure.include: "*"

# Configuraci贸n de logging para ayudar en la depuraci贸n
logging:
  level:
    root: INFO
    '[org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator]': INFO
    '[org.springframework.cloud.gateway]': TRACE
    '[org.springframework.security]': DEBUG

