spring:
  application:
    name: edge-server

server:
  port: 8081
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/edge.p12
    key-store-password: password
    key-alias: localhost

jwt:
  secret: mi-super-clave-jwt-muy-segura-12345678

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: mi-super-clave-jwt-muy-segura-12345678

  cloud:
    gateway:
      # Filtros por defecto
      default-filters:
        - TokenRelay

      # Configuración de CORS global
      globalcors:
        corsConfigurations:
          '[/**]':
            # Orígenes permitidos; cambia "*" por tus dominios si usas cookies.
            allowedOrigins: "*"
            # Métodos HTTP permitidos
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            # Cabeceras permitidas
            allowedHeaders: "*"
            # Si vas a enviar credenciales (cookies, auth headers), descomenta y reemplaza "*" por dominios concretos.
            # allowCredentials: true
            # Duración máxima de caché de la preflight en segundos
            maxAge: 3600

      # Rutas y sus filtros
      routes:
        - id: ms-user
          uri: lb://ms-user
          predicates:
            - Path=/ms-user/**
          filters:
            - StripPrefix=1

        - id: ms-user-swagger-ui
          uri: lb://ms-user
          predicates:
            - Path=/swagger-user/swagger-ui/**
          filters:
            - StripPrefix=1

        - id: ms-user-swagger-config
          uri: lb://ms-user
          predicates:
            - Path=/v3/api-docs/swagger-config
          filters:
            - StripPrefix=0

        - id: ms-user-swagger-api-docs-fix
          uri: lb://ms-user
          predicates:
            - Path=/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/ms-auth/**
          filters:
            - StripPrefix=1

        - id: ms-anuncios
          uri: lb://ms-anuncios
          predicates:
            - Path=/ms-anuncios/**
          filters:
            - StripPrefix=1

        - id: ms-rating
          uri: lb://ms-rating
          predicates:
            - Path=/ms-rating/**
          filters:
            - StripPrefix=1

        - id: eureka-web-start
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: eureka-web-other
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/**

management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    '[org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator]': INFO
    '[org.springframework.cloud.gateway]': TRACE
    '[org.springframework.security]': DEBUG
