# ————————————————————————————————————————————————
#  CONFIG SERVER :  microservicio ms-anuncios
# ————————————————————————————————————————————————

server:
  port: ${SERVER_PORT:7005}

jwt:
  secret: mi-super-clave-jwt-muy-segura-12345678     # ⬅️ igual que en users

spring:
  application:
    name: ms-anuncios

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${jwt.secret}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    #password: ${SPRING_DATASOURCE_PASSWORD}
    password: '{cipher}7cfc0d39c02f3db1f7119f88164d2826433fafda3777659925982ea4cd16f5be'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update          # ⇦ lo tenías local; pasa al Config Server

  config:
    import:
      - "classpath:application-openapi-anuncio.yml"
      - "classpath:application-openapi-tag.yml"

# — Eureka ————————————————————————————————————————
app.eureka-server: eureka-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

---
spring.config.activate.on-profile: docker

# Ejemplo de override para Docker (puedes ampliarlo)
#spring:
#  datasource:
#    url: jdbc:postgresql://postgres:5432/anuncios_db
#    username: postgres
#    password: pass123
