server:
  port: ${SERVER_PORT:5066}

jwt:
  secret: mi-super-clave-jwt-muy-segura-12345678

spring:
  application:
    name: ms-chat
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: mi-super-clave-jwt-muy-segura-12345678

  cloud:
    config:
      uri: http://localhost:8888
      username: config-usr
      password: SIS313ucb

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: '{cipher}7cfc0d39c02f3db1f7119f88164d2826433fafda3777659925982ea4cd16f5be'
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

  config:
    import:
      - "classpath:application-openapi-mschat.yml"

---
spring.config.activate.on-profile: docker
