server:
  port: ${SERVER_PORT:5008}


jwt:
  secret: mi-super-clave-jwt-muy-segura-12345678
  
spring:
  application:
    name: ms-rating
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db-rating:5432/ms-rating-db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: '{cipher}e5d596d9a3ead362d030a41afaa130bd95ac7e2120246e33a7e7ee1cdc03a8b141b283cdbee52741241f5288139bfc0a'
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: mi-super-clave-jwt-muy-segura-12345678
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
config:
  import:
    - "classpath:application-openapi-rating.yml"

---
spring.config.activate.on-profile: docker