server:
  port: ${SERVER_PORT:7002}

#spring.datasource.url: jdbc:postgresql://localhost:5432/ms_user_hazmelaucb_db
#spring.datasource.username: postgres
#spring.datasource.password: '{cipher}a653d46baf8307a2256ad22a1c0fcc78dc783829c126a842d74c100adec3f0b9'
jwt:
  secret: mi-super-clave-jwt-muy-segura-12345678

spring:
  application:
    name: ms-user

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: mi-super-clave-jwt-muy-segura-12345678

  datasource:
    #url: jdbc:postgresql://localhost:5432/ms_user_hazmelaucb_db
    #username: postgres
    #password: '{cipher}7cfc0d39c02f3db1f7119f88164d2826433fafda3777659925982ea4cd16f5be'
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    #password: ${SPRING_DATASOURCE_PASSWORD}
    password: '{cipher}7cfc0d39c02f3db1f7119f88164d2826433fafda3777659925982ea4cd16f5be'
    driver-class-name: org.postgresql.Driver
    
  config:
    import:
      - "classpath:application-openapi-admin.yml"
      - "classpath:application-openapi-student.yml"
      - "classpath:application-openapi-user.yml"

---
spring.config.activate.on-profile: docker

#datasource:
    #url: jdbc:postgresql://localhost:5432/ms_user_hazmelaucb_db
    #username: postgres
    #password: pass123
    #url: ${SPRING_DATASOURCE_URL}
    #username: ${SPRING_DATASOURCE_USERNAME}
    #password: ${SPRING_DATASOURCE_PASSWORD}
    #driver-class-name: org.postgresql.Driver
